import { Settings, type AppSnapshot, type Connection, type ModelRecord } from './contracts'

export const DEFAULT_SETTINGS = Settings.parse({})
export const CONNECTIONS: Connection[] = [
  {
    id: 'codex',
    name: 'Codex',
    description: 'Implementation, investigation, and verified changes.',
    status: 'disconnected',
    capabilities: ['Code', 'Tools', 'Worktrees'],
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'A second perspective for reviews and complex tasks.',
    status: 'disconnected',
    capabilities: ['Review', 'Reasoning'],
  },
  {
    id: 'automation',
    name: 'Controls you approve',
    description: 'Press a named control in an application, after you approve the exact one.',
    status: 'disconnected',
    capabilities: ['Accessibility'],
  },
  {
    id: 'apple-calendar',
    name: 'Apple Calendar',
    description: 'Your schedule, with changes you approve.',
    status: 'disconnected',
    capabilities: ['Events', 'Availability'],
  },
  {
    id: 'apple-reminders',
    name: 'Reminders',
    description: 'Capture the things you want to follow through on.',
    status: 'disconnected',
    capabilities: ['Lists', 'Reminders'],
  },
  {
    id: 'apple-mail',
    name: 'Apple Mail',
    description: 'Read selected mail and prepare considered replies.',
    status: 'disconnected',
    capabilities: ['Mail', 'Drafts'],
  },
  {
    id: 'google',
    name: 'Google',
    description: 'Gmail, Calendar, and Drive with scoped access.',
    status: 'disconnected',
    capabilities: ['Gmail', 'Calendar', 'Drive'],
  },
  {
    id: 'browser',
    name: 'Browser context',
    description: 'Share the tab you choose from Safari or Chrome.',
    status: 'disconnected',
    capabilities: ['Selected tab', 'Page context'],
  },
  {
    id: 'mcp',
    name: 'Custom tools',
    description: 'Connect a reviewed local MCP server.',
    status: 'disconnected',
    capabilities: ['MCP'],
  },
]
export const MODELS: ModelRecord[] = [
  {
    id: 'parakeet',
    name: 'Parakeet',
    repository: 'mlx-community/parakeet-tdt-0.6b-v3',
    role: 'asr',
    description: 'Accurate local speech recognition.',
    sizeLabel: '0.6B parameters',
    status: 'absent',
    experimental: false,
    installable: false,
    qualified: false,
    license: 'CC-BY-4.0',
  },
  {
    id: 'kokoro',
    name: 'Kokoro',
    repository: 'mlx-community/Kokoro-82M-bf16',
    role: 'tts',
    description: 'Natural speech, including your British voice.',
    sizeLabel: '82M parameters',
    status: 'absent',
    experimental: false,
    installable: false,
    qualified: false,
    license: 'Apache-2.0',
  },
  {
    id: 'qwen',
    name: 'Qwen 3.5',
    repository: 'mlx-community/Qwen3.5-4B-4bit',
    role: 'reasoning',
    description: 'Your local reasoning and visual understanding.',
    sizeLabel: '4B · 4-bit',
    status: 'absent',
    experimental: false,
    installable: false,
    qualified: false,
    license: 'Apache-2.0',
  },
  {
    id: 'embedding',
    name: 'Qwen Embedding',
    repository: 'mlx-community/Qwen3-Embedding-0.6B-4bit-DWQ',
    role: 'embedding',
    description: 'Find the memories that matter to this moment.',
    sizeLabel: '0.6B · 4-bit',
    status: 'absent',
    experimental: false,
    installable: false,
    qualified: false,
    license: 'Apache-2.0',
  },
  {
    id: 'whisper',
    name: 'Whisper',
    repository: 'mlx-community/whisper-small-mlx',
    role: 'asr',
    description: 'An independent local transcription fallback.',
    sizeLabel: '244M parameters',
    status: 'absent',
    experimental: false,
    installable: false,
    qualified: false,
    license: 'MIT',
  },
  {
    id: 'silero',
    name: 'Silero VAD',
    repository: 'onnx-community/silero-vad',
    role: 'vad',
    description: 'Recognize speech activity and interruptions.',
    sizeLabel: 'Compact ONNX',
    status: 'absent',
    experimental: false,
    installable: false,
    qualified: false,
    license: 'MIT',
  },
  {
    id: 'smart-turn',
    name: 'Smart Turn',
    repository: 'pipecat-ai/smart-turn-v3',
    role: 'turn',
    description: 'Understand when you have finished your thought.',
    sizeLabel: 'Compact ONNX',
    status: 'absent',
    experimental: false,
    installable: false,
    qualified: false,
    license: 'BSD-2-Clause',
  },
  {
    id: 'lfm',
    name: 'LFM Audio',
    repository: 'mlx-community/LFM2.5-Audio-1.5B-4bit',
    role: 'duplex',
    description: 'A lightweight speech-to-speech research profile.',
    sizeLabel: '1.5B · 4-bit',
    status: 'absent',
    experimental: true,
    installable: false,
    qualified: false,
    license: 'LFM license',
  },
  {
    id: 'nemotron',
    name: 'Nemotron VoiceChat',
    repository: 'mlx-community/NemotronLabs-VoiceChat-11B-4bit',
    role: 'duplex',
    description: 'Speech and function-channel qualification.',
    sizeLabel: '11B · 4-bit',
    status: 'absent',
    experimental: true,
    installable: false,
    qualified: false,
    license: 'OpenMDW-1.1',
  },
  {
    id: 'minicpm',
    name: 'MiniCPM-o',
    repository: 'openbmb/MiniCPM-o-4_5',
    role: 'duplex',
    description: 'Multimodal duplex research; requires a qualified Mac runtime.',
    sizeLabel: 'Omni · research',
    status: 'absent',
    experimental: true,
    installable: false,
    qualified: false,
    license: 'Apache-2.0',
  },
  {
    id: 'ui-tars',
    name: 'UI-TARS',
    repository: 'mlx-community/UI-TARS-1.5-7B-4bit',
    role: 'vision',
    description: 'Visual grounding qualification for selected interfaces.',
    sizeLabel: '7B · 4-bit',
    status: 'absent',
    experimental: true,
    installable: false,
    qualified: false,
    license: 'Apache-2.0',
  },
]

export function emptySnapshot(): AppSnapshot {
  return {
    version: 1,
    settings: structuredClone(DEFAULT_SETTINGS),
    voice: { phase: 'off', level: 0, partial: '', generation: 0 },
    tasks: [],
    events: [],
    approvals: [],
    receipts: [],
    messages: [],
    memories: [],
    routines: [],
    projects: [],
    vault: {
      scope: 'personal',
      notes: 0,
      chunks: 0,
      embedded: 0,
      bytes: 0,
      skipped: 0,
      redacted: 0,
      syncing: false,
    },
    connections: structuredClone(CONNECTIONS),
    models: structuredClone(MODELS),
    permissions: { microphone: 'not-determined', screen: 'not-determined', accessibility: false },
    diagnostics: {
      platform: 'macOS',
      chip: 'Apple silicon',
      memoryGB: 0,
      appMemoryMB: 0,
      glass: false,
      locked: false,
      native: false,
      modelRuntime: false,
      databaseEncrypted: false,
      workerErrors: [],
    },
  }
}
